### ISSUE TITLE
Examples doesn't start with the latest tip

### ISSUE THREAD

**Issue by slajar** [sriharshachilakapati/WebGL4J#5] opened 2017-03-23 20:43 UTC
I checked out a fresh copy from the repository and ran:
"./gradlew clean build superDev"

Unfortunately, it does not start up your examples page. It delivers a blank grey screen. 

I actually, tried to use "dev mode on" "compile"... It seems to compile forever. 

Do you have any idea what is going on?

**Comment by sriharshachilakapati** [comment] 2017-03-24 06:51
Confirmed this as well. Might have been because of the 2.8.0-Beta build of the compiler. Compiling with the `-strict` mode gives this output:

~~~
Mar 24, 2017 12:15:47 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Compiling module com.shc.webgl4j.examples.client
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.SizeValidatorForArraysOfBoolean'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/SizeValidatorForArraysOfBoolean.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected package "org.hibernate.validator.super.org.hibernate.validator.constraints.impl"
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.SizeValidatorForArray'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/SizeValidatorForArray.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected package "org.hibernate.validator.super.org.hibernate.validator.constraints.impl"
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.SizeValidatorForArraysOfShort'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/SizeValidatorForArraysOfShort.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected package "org.hibernate.validator.super.org.hibernate.validator.constraints.impl"
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.SizeValidatorForArraysOfLong'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/SizeValidatorForArraysOfLong.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected package "org.hibernate                   .validator.super.org.hibernate.validator.constraints.impl"
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.SizeValidatorForArraysOfByte'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/SizeValidatorForArraysOfByte.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected package "org.hibernate.validator.super.org.hibernate.validator.constraints.impl"
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.SizeValidatorForArraysOfFloat'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/SizeValidatorForArraysOfFloat.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected package "org.hibernate.validator.super.org.hibernate.validator.constraints.impl"
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.SizeValidatorForArraysOfInt'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/SizeValidatorForArraysOfInt.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected package "org.hibernate.validator.super.org.hibernate.validator.constraints.impl"
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.PatternValidator'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/PatternValidator.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected package "org.hibernate.validator.super.org.hibernate.validator.constraints.impl"
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.ScriptAssertValidator'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/ScriptAssertValidator.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected package "org.hibernate.validator.super.org.hibernate.validator.constraints.impl"
         [ERROR] Line 20: The import org.hibernate.validator.constraints cannot be resolved
         [ERROR] Line 26: Email cannot be resolved to a type
   Tracing compile failure path for type 'org.hibernate.validator.engine.ValidationSupport'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/engine/ValidationSupport.java'
         [ERROR] Line 46: PathImpl cannot be resolved to a type
         [ERROR] Line 43: ConstraintViolationImpl cannot be resolved to a type
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.EmailValidator'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-u                                                     ser/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/EmailValidator.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected package "org.hibernate.validator.super.org.hibernate.validator.constraints.impl"
         [ERROR] Line 20: The import org.hibernate.validator.constraints cannot be resolved
         [ERROR] Line 25: Email cannot be resolved to a type
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.engine.PathImpl'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/engine/PathImpl.java'
         [ERROR] Line 72: NodeImpl cannot be resolved to a type
         [ERROR] Line 84: NodeImpl cannot be resolved to a type
         [ERROR] Line 131: NodeImpl cannot be resolved to a type
         [ERROR] Line 202: NodeImpl cannot be resolved to a type
         [ERROR] Line 95: NodeImpl cannot be resolved to a type
         [ERROR] Line 127: NodeImpl cannot be resolved to a type
         [ERROR] Line 19: The declared package "org.hibernate.validator.engine" does not match the expected package "org.hibernate.validator.super.org.hibernate.validator.engine"
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.SizeValidatorForArraysOfChar'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/SizeValidatorForArraysOfChar.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected packag                                   e "org.hibernate.validator.super.org.hibernate.validator.constraints.impl"
   Tracing compile failure path for type 'org.joml.sampling.Random'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/org.joml/joml-gwt/1.9.2-SNAPSHOT/be8561a382c30c9022c466141dcbf1e9cf0bcd4/joml-gwt-1.9.2-SNAPSHOT.jar!/org/joml/sampling/Random.java'
         [ERROR] Line 44: The method getDeclaredMethod(String, Class[]) is undefined for the type Class<Long>
   Tracing compile failure path for type 'org.hibernate.validator.engine.ConstraintViolationImpl_CustomFieldSerializer'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/engine/ConstraintViolationImpl_CustomFieldSerializer.java'
         [ERROR] Line 100: The method instantiate(SerializationStreamReader) from the type ConstraintViolationImpl_CustomFieldSerializer refers to the missing type ConstraintViolationImpl
         [ERROR] Line 37: ConstraintViolationImpl cannot be resolved to a type
         [ERROR] Line 73: ConstraintViolationImpl cannot be resolved to a type
         [ERROR] Line 32: The type ConstraintViolationImpl_CustomFieldSerializer must implement the inherited abstract method CustomFieldSerializer<ConstraintViolationImpl>.deserializeInstance(SerializationStreamReader, ConstraintViolationImpl)
         [ERROR] Line 33: ConstraintViolationImpl cannot be resolved to a type
         [ERROR] Line 32: The type ConstraintViolationImpl_CustomFieldSerializer must implement the inherited abstract method CustomFieldSerializer<ConstraintViolationImpl>.serializeInstance(SerializationStreamWriter, ConstraintViolationImpl)
         [ERROR] Line 41: ConstraintViolationImpl cannot be resolved to a type
         [ERROR] Line 105: ConstraintViolationImpl cannot be resolved to a type
         [ERROR] Line 88: ConstraintViolationImpl cannot be resolved to a type
         [ERROR] Line 53: ConstraintViolationImpl cannot be resolved to a type
         [ERROR] Line 98: ConstraintViolationImpl cannot be resolved to a type
   Tracing compile failure path for type 'org.hibernate.validator.engine.PathImpl_CustomFieldSerializer'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/engine/PathImpl_CustomFieldSerializer.java'
         [ERROR] Line 39: PathImpl cannot be resolved
         [ERROR] Line 61: The method instantiate(SerializationStreamReader) from the type PathImpl_CustomFieldSerializer refers to the missing type PathImpl
         [ERROR] Line 59: PathImpl cannot be resolved to a type
         [ERROR] Line 49: PathImpl cannot be resolved to a type
         [ERROR] Line 35: PathImpl cannot be resolved to a type
         [ERROR] Line 43: PathImpl cannot be resolved to a type
         [ERROR] Line 26: The type PathImpl_CustomFieldSerializer must implement the inherited abstract method CustomFieldSerializer<PathImpl>.serializeInstance(SerializationStreamWriter, PathImpl)
         [ERROR] Line 27: PathImpl cannot be resolved to a type
         [ERROR] Line 31: PathImpl cannot be resolved to a type
         [ERROR] Line 66: PathImpl cannot be resolved to a type
         [ERROR] Line 26: The type PathImpl_CustomFieldSerializer must implement the inherited abstract method CustomFieldSerializer<PathImpl>.deserializeInstance(SerializationStreamReader, PathImpl)
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.FutureValidatorForCalendar'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/FutureValidatorForCalendar.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected package "org.hibernate.validator.super.org.hibernate.validator.constraints.impl"
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.URLValidator'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/URLValidator.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected package "org.hibernate.validator.super.org.hibernate.validator.constraints.impl"
         [ERROR] Line 20: The import org.hibernate.validator.constraints cannot be resolved
         [ERROR] Line 26: URL cannot be resolved to a type
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.PastValidatorForCalendar'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/PastValidatorForCalendar.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected package "org.hibernate.validator.super.org.hibernate.validator.constraints.impl"
   Tracing compile failure path for type 'org.hibernate.validator.super.org.hibernate.validator.constraints.impl.SizeValidatorForArraysOfDouble'
      [ERROR] Errors in 'jar:file:/C:/Users/Harsha/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-beta1/abea2e34826ce592e0d2bd49a844b2ff57b78134/gwt-user-2.8.0-beta1.jar!/org/hibernate/validator/super/org/hibernate/validator/constraints/impl/SizeValidatorForArraysOfDouble.java'
         [ERROR] Line 16: The declared package "org.hibernate.validator.constraints.impl" does not match the expected package "org.hibernate.validator.super.org.hibernate.validator.constraints.impl"
   [ERROR] Aborting compile due to errors in some input files
:examples:compileGwt FAILED
~~~

I don't even know why it is building hibernate when I'm not using it at all. This might be already fixed in the 2.8.0 release of GWT compiler, but the gradle plugin doesn't yet support this compiler. Will let you know once the fix is done.

**Comment by sriharshachilakapati** [comment] 2017-03-24 16:25
I found that it is dependent on the JOML dependency: https://github.com/JOML-CI/JOML/issues/109

**Comment by slajar** [comment] 2017-03-24 20:09
thanks, using the 1.9.3 joml makes it working again 👍

**Closed as completed** 2017-08-21 15:08 UTC
Labels: bug
